version: '3.8'

services:
  db:
    container_name: espresso_diary_db
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: coffee-diary
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres: